/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AkunController;
import Controller.DaftarMejaController;
import Controller.HistoryBookingController;
import Controller.RestoranController;
import Model.DaftarMeja;
import Model.DriverBookingMeja;
import Model.HistoryBooking;
import Model.PemilikResto;
import Model.Restoran;
import Model.SesiLogin;
import View.Components.TambahAdmin;
import View.Components.UbahNamaUser;
import View.Components.UbahNoTelpon;
import View.Components.UbahPassword;
import View.Components.UbahUsername;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuPemesan
     */
    private HistoryBookingController hisbookCNTRL;
    private DaftarMejaController dafmejaCNTRL;
    private RestoranController restoCNTRL;
    private AkunController akunCNTRL;
    private DriverBookingMeja driver;
    private DefaultTableModel ModelLaporanBooking, modelDataResto;
    
    public MenuAdmin() {
        
        initComponents();
        
        hisbookCNTRL = new HistoryBookingController();
        dafmejaCNTRL = new DaftarMejaController();
        akunCNTRL = new AkunController();
        restoCNTRL = new RestoranController();
        driver = new DriverBookingMeja(this);
        
        namaAdminDisplay.setText(SesiLogin.getNama());
        totalDisplay.setText(String.valueOf(hisbookCNTRL.getTotalTransaksi()));
        NamaUserProfile.setText(SesiLogin.getNama());
        NoTelpUserProfile.setText(SesiLogin.getNoTelpon());
        UsernameUserProfile.setText(SesiLogin.getUsername());
        
        String[] judul = {"id History", "nama pemesan", "nama resto", "tanggal datang", "status"};
        ModelLaporanBooking = new DefaultTableModel(judul, 0);
        tableLaporanBooking.setModel(ModelLaporanBooking);
        loadLaporanBooking();
        
        String[] judulDataResto = {"id meja", "id restoran", "jumlah kursi", "status"};
        modelDataResto = new DefaultTableModel(judulDataResto, 0);
        tableDataResto.setModel(modelDataResto);
    }
    
    public void loadLaporanBooking(){
        List<HistoryBooking> dataBooking = hisbookCNTRL.getAllHistoryBooking();
        
        for(HistoryBooking hisbook : dataBooking){
            Object[] rowData = {
                hisbook.getIdHistoryBooking(),
                hisbook.getNama_pemesan(),
                hisbook.getNamaRestoran(),
                hisbook.getWaktuDatang(),
                hisbook.getStatus()
            };
            ModelLaporanBooking.addRow(rowData);
        }
    }
    
    public void loadDataMejaResto(int idresto){
        List<DaftarMeja> dataMeja = dafmejaCNTRL.getAllDaftarMeja(idresto);
        
        for(DaftarMeja dafmeja : dataMeja){
            Object[] rowdatameja = {
                dafmeja.getIdMeja(),
                dafmeja.getIdResto(),
                dafmeja.getJumlahKursi(),
                dafmeja.getStatus(),
            };
            modelDataResto.addRow(rowdatameja);
        }
   }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        namaAdminDisplay = new javax.swing.JLabel();
        tambahAdmin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLaporanBooking = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        refreshBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        totalDisplay = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        namaRetsoInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CariBTN = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        namaRestoDisplay = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        alamatRestoDisplay = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDataResto = new javax.swing.JTable();
        RefreshBTN2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        idRestoDisplay = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        NamaUserProfile = new javax.swing.JLabel();
        UbahPassword = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        UbahNama = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        UbahNoTelpon = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        NoTelpUserProfile = new javax.swing.JLabel();
        LogoutBTN = new javax.swing.JButton();
        UsernameUserProfile = new javax.swing.JLabel();
        UbahUsername = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Selamat Datang");

        namaAdminDisplay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namaAdminDisplay.setText("nama admin");

        tambahAdmin.setText("Tambah Admin");
        tambahAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahAdminActionPerformed(evt);
            }
        });

        jLabel3.setText("Tambah Admin");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaAdminDisplay))
                    .addComponent(tambahAdmin)
                    .addComponent(jLabel3))
                .addContainerGap(549, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaAdminDisplay))
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tambahAdmin)
                .addContainerGap(359, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Home", jPanel4);

        tableLaporanBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableLaporanBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLaporanBookingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableLaporanBooking);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Daftar Laporan Booking");

        jLabel5.setText("Refresh Table");

        refreshBTN.setText("Refresh");
        refreshBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBTNActionPerformed(evt);
            }
        });

        jLabel1.setText("Total Transaksi: ");

        totalDisplay.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        totalDisplay.setText("jLabel6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(261, 582, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(refreshBTN)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalDisplay)))
                        .addGap(66, 66, 66))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshBTN)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(totalDisplay))))
                .addContainerGap(296, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Daftar Laporan Booking", jPanel1);

        jLabel6.setText("Cari Restoran");

        CariBTN.setText("Cari");
        CariBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariBTNActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("DATA RESTORAN");

        jLabel8.setText("Nama Restoran");

        namaRestoDisplay.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        namaRestoDisplay.setText("display");

        jLabel9.setText("Alamat Restoran");

        alamatRestoDisplay.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        alamatRestoDisplay.setText("display");

        tableDataResto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableDataResto);

        RefreshBTN2.setText("Refresh");
        RefreshBTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshBTN2ActionPerformed(evt);
            }
        });

        jLabel10.setText("ID Resto");

        idRestoDisplay.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        idRestoDisplay.setText("display");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(CariBTN)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(namaRetsoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(RefreshBTN2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idRestoDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaRestoDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alamatRestoDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaRetsoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CariBTN)
                .addGap(41, 41, 41)
                .addComponent(jLabel7)
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(idRestoDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(namaRestoDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(alamatRestoDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RefreshBTN2))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Cari Resto", jPanel5);

        NamaUserProfile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NamaUserProfile.setText("nama user");

        UbahPassword.setText("Ubah Password");
        UbahPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahPasswordActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Nama:");

        UbahNama.setText("Ubah Nama");
        UbahNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahNamaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Username:");

        UbahNoTelpon.setText("Ubah no Telpon");
        UbahNoTelpon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahNoTelponActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("No Telpon:");

        NoTelpUserProfile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NoTelpUserProfile.setText("no telpon user");

        LogoutBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LogoutBTN.setText("Logout");
        LogoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBTNActionPerformed(evt);
            }
        });

        UsernameUserProfile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UsernameUserProfile.setText("username user");

        UbahUsername.setText("Ubah Username");
        UbahUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahUsernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(UbahNama)
                        .addGap(203, 203, 203)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(14, 14, 14)
                                .addComponent(UsernameUserProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(UbahUsername)
                                .addGap(345, 345, 345))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(47, 47, 47)
                                .addComponent(NamaUserProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(UbahPassword)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(302, 302, 302)
                                .addComponent(LogoutBTN))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(10, 10, 10)
                                .addComponent(NoTelpUserProfile))
                            .addComponent(UbahNoTelpon))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(NamaUserProfile)
                    .addComponent(jLabel12)
                    .addComponent(UsernameUserProfile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UbahNama)
                    .addComponent(UbahUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UbahPassword)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(NoTelpUserProfile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UbahNoTelpon)
                .addGap(60, 60, 60)
                .addComponent(LogoutBTN)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Profile", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBTNActionPerformed
        tableLaporanBooking.removeAll();
        totalDisplay.setText(String.valueOf(0));
        int rows = ModelLaporanBooking.getRowCount();
        for(int i = rows - 1; i >= 0; i--){
            ModelLaporanBooking.removeRow(i);
        }
        totalDisplay.setText(String.valueOf(hisbookCNTRL.getTotalTransaksi()));
        loadLaporanBooking();
    }//GEN-LAST:event_refreshBTNActionPerformed

    private void tableLaporanBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLaporanBookingMouseClicked
        int selectedRow = tableLaporanBooking.getSelectedRow();

        if (selectedRow != -1) {

        }
    }//GEN-LAST:event_tableLaporanBookingMouseClicked

    private void tambahAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahAdminActionPerformed
        TambahAdmin tmbhadmin = new TambahAdmin();
        tmbhadmin.setVisible(true);
    }//GEN-LAST:event_tambahAdminActionPerformed

    private void CariBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariBTNActionPerformed
        String namaresto = namaRetsoInput.getText();
        
        Restoran newResto = restoCNTRL.getRestoByNama(namaresto);
        if (newResto != null) {
            idRestoDisplay.setText(String.valueOf(newResto.getIdRestoran()));
            namaRestoDisplay.setText(newResto.getNamaResto());
            alamatRestoDisplay.setText(newResto.getAlamat());
            loadDataMejaResto(newResto.getIdRestoran());
        } else {
            JOptionPane.showMessageDialog(null, "Restoran tidak ditemukan");
        }
        
    }//GEN-LAST:event_CariBTNActionPerformed

    private void RefreshBTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshBTN2ActionPerformed
            idRestoDisplay.setText("");
            namaRestoDisplay.setText("");
            alamatRestoDisplay.setText("");
            
            tableDataResto.removeAll();
            int rows = modelDataResto.getRowCount();
            for(int i = rows - 1; i >= 0; i--){
                modelDataResto.removeRow(i);
            }
    }//GEN-LAST:event_RefreshBTN2ActionPerformed

    private void UbahPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahPasswordActionPerformed
        UbahPassword changePassword = new UbahPassword();
        changePassword.setVisible(true);
    }//GEN-LAST:event_UbahPasswordActionPerformed

    private void UbahNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahNamaActionPerformed
        UbahNamaUser changeName = new UbahNamaUser();
        changeName.setVisible(true);
    }//GEN-LAST:event_UbahNamaActionPerformed

    private void UbahNoTelponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahNoTelponActionPerformed
        UbahNoTelpon changeNoTelpon = new UbahNoTelpon();
        changeNoTelpon.setVisible(true);
    }//GEN-LAST:event_UbahNoTelponActionPerformed

    private void LogoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBTNActionPerformed
        SesiLogin.clearSesiLogin();

        Login LoginScreen = new Login();
        LoginScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutBTNActionPerformed

    private void UbahUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahUsernameActionPerformed
        UbahUsername changeUsername = new UbahUsername();
        changeUsername.setVisible(true);
    }//GEN-LAST:event_UbahUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CariBTN;
    private javax.swing.JButton LogoutBTN;
    private javax.swing.JLabel NamaUserProfile;
    private javax.swing.JLabel NoTelpUserProfile;
    private javax.swing.JButton RefreshBTN2;
    private javax.swing.JButton UbahNama;
    private javax.swing.JButton UbahNoTelpon;
    private javax.swing.JButton UbahPassword;
    private javax.swing.JButton UbahUsername;
    private javax.swing.JLabel UsernameUserProfile;
    private javax.swing.JLabel alamatRestoDisplay;
    private javax.swing.JLabel idRestoDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel namaAdminDisplay;
    private javax.swing.JLabel namaRestoDisplay;
    private javax.swing.JTextField namaRetsoInput;
    private javax.swing.JButton refreshBTN;
    private javax.swing.JTable tableDataResto;
    private javax.swing.JTable tableLaporanBooking;
    private javax.swing.JButton tambahAdmin;
    private javax.swing.JLabel totalDisplay;
    // End of variables declaration//GEN-END:variables
}
