/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DaftarMejaController;
import Controller.HistoryBookingController;
import Controller.RestoranController;
import Model.DaftarMeja;
import Model.DriverBookingMeja;
import Model.HistoryBooking;
import Model.Restoran;
import Model.SesiLogin;
import View.Components.BookingMeja;
import View.Components.UbahNamaUser;
import View.Components.UbahUsername;
import View.Components.UbahPassword;
import View.Components.UbahNoTelpon;
import View.Components.cancelPemesanan;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MenuPemesan extends javax.swing.JFrame {

    /**
     * Creates new form MenuPemesan
     */
    private DriverBookingMeja driver;
    private RestoranController restoCNTRL;
    private DaftarMejaController dafMejaCNTRL;
    private HistoryBookingController historyCNTRL;
    private DefaultTableModel modelDaftarMeja, modelHistoryBook;
    
    public MenuPemesan() {
        driver = new DriverBookingMeja(this);
        restoCNTRL = new RestoranController();
        dafMejaCNTRL = new DaftarMejaController();
        historyCNTRL = new HistoryBookingController();
        initComponents();
        
        int idUser = SesiLogin.getId();
        namaPemesanDisplay.setText(SesiLogin.getNama());
        NamaUserProfile.setText(SesiLogin.getNama());
        NoTelpUserProfile.setText(SesiLogin.getNoTelpon());
        UsernameUserProfile.setText(SesiLogin.getUsername());
    
        String[] judulTableMeja = {"id meja", "id restoran","jumlah kursi", "status"};
        modelDaftarMeja = new DefaultTableModel(judulTableMeja, 0);
        daftarMejaResto.setModel(modelDaftarMeja);
        
        String[] judulTableHistory = {"id history","nama restoran", "id meja", "waktu datang", "status pemesanan"};
        modelHistoryBook = new DefaultTableModel(judulTableHistory, 0);
        daftarRiwayatBook.setModel(modelHistoryBook);
        loadRiawayatBooking(idUser);
        
    }
    
    public void loadDaftarMejaByNamaResto(String namaresto, int idResto){
        List<DaftarMeja> dataMeja = dafMejaCNTRL.getAllDaftarMeja(idResto);
        
        for(DaftarMeja dafmeja : dataMeja){
            Object[] rowdatameja = {
                dafmeja.getIdMeja(),
                dafmeja.getIdResto(),
                dafmeja.getJumlahKursi(),
                dafmeja.getStatus(),
            };
            modelDaftarMeja.addRow(rowdatameja);
        }
    }
    
    public void loadRiawayatBooking(int idAkun){
        List<HistoryBooking> dataHistory = historyCNTRL.getHistoryBookByIdUser(idAkun);
        
        for(HistoryBooking hisbook : dataHistory){
            Object[] rowdatahistory = {
                hisbook.getIdResto(),
                hisbook.getNamaRestoran(),
                hisbook.getIdMeja(),
                hisbook.getWaktuDatang(),
                hisbook.getStatus()
            };
            modelHistoryBook.addRow(rowdatahistory);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        namaPemesanDisplay = new javax.swing.JLabel();
        cariRestoInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cariBTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        namaRestoDisplay = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        daftarMejaResto = new javax.swing.JTable();
        RefreshBTN02 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        daftarRiwayatBook = new javax.swing.JTable();
        RefreshBTN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        UsernameUserProfile = new javax.swing.JLabel();
        UbahUsername = new javax.swing.JButton();
        NamaUserProfile = new javax.swing.JLabel();
        UbahPassword = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        UbahNama = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        UbahNoTelpon = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        NoTelpUserProfile = new javax.swing.JLabel();
        LogoutBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Selamat Datang");

        namaPemesanDisplay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namaPemesanDisplay.setText("nama user");

        jLabel4.setText("Cari Restoran");

        cariBTN.setText("cari");
        cariBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBTNActionPerformed(evt);
            }
        });

        jLabel5.setText("Menampilkan Daftar Meja Di Restoran");

        namaRestoDisplay.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        namaRestoDisplay.setText("nama Resto");

        daftarMejaResto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        daftarMejaResto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftarMejaRestoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(daftarMejaResto);

        RefreshBTN02.setText("Refresh");
        RefreshBTN02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshBTN02ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaPemesanDisplay))
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cariRestoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cariBTN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaRestoDisplay))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RefreshBTN02)))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaPemesanDisplay))
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariRestoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariBTN))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(namaRestoDisplay))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RefreshBTN02))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home", jPanel1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Riwayat Booking");

        daftarRiwayatBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        daftarRiwayatBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftarRiwayatBookMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(daftarRiwayatBook);

        RefreshBTN.setText("Refresh");
        RefreshBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RefreshBTN)))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RefreshBTN))
                .addContainerGap(270, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Riwayat booking", jPanel2);

        UsernameUserProfile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UsernameUserProfile.setText("username user");

        UbahUsername.setText("Ubah Username");
        UbahUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahUsernameActionPerformed(evt);
            }
        });

        NamaUserProfile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NamaUserProfile.setText("nama user");

        UbahPassword.setText("Ubah Password");
        UbahPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahPasswordActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nama:");

        UbahNama.setText("Ubah Nama");
        UbahNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahNamaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Username:");

        UbahNoTelpon.setText("Ubah no Telpon");
        UbahNoTelpon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahNoTelponActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("No Telpon:");

        NoTelpUserProfile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NoTelpUserProfile.setText("no telpon user");

        LogoutBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LogoutBTN.setText("Logout");
        LogoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(UbahNama)
                        .addGap(203, 203, 203)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(14, 14, 14)
                                .addComponent(UsernameUserProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(UbahUsername)
                                .addGap(345, 345, 345))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(47, 47, 47)
                                .addComponent(NamaUserProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(UbahPassword)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(302, 302, 302)
                                .addComponent(LogoutBTN))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(10, 10, 10)
                                .addComponent(NoTelpUserProfile))
                            .addComponent(UbahNoTelpon))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NamaUserProfile)
                    .addComponent(jLabel3)
                    .addComponent(UsernameUserProfile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UbahNama)
                    .addComponent(UbahUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UbahPassword)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(NoTelpUserProfile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UbahNoTelpon)
                .addGap(60, 60, 60)
                .addComponent(LogoutBTN)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Profile", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UbahUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahUsernameActionPerformed
        UbahUsername changeUsername = new UbahUsername();
        changeUsername.setVisible(true);
    }//GEN-LAST:event_UbahUsernameActionPerformed

    private void UbahPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahPasswordActionPerformed
        UbahPassword changePassword = new UbahPassword();
        changePassword.setVisible(true);
    }//GEN-LAST:event_UbahPasswordActionPerformed

    private void UbahNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahNamaActionPerformed
        UbahNamaUser changeName = new UbahNamaUser();
        changeName.setVisible(true);
    }//GEN-LAST:event_UbahNamaActionPerformed

    private void UbahNoTelponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahNoTelponActionPerformed
        UbahNoTelpon changeNoTelpon = new UbahNoTelpon();
        changeNoTelpon.setVisible(true);
    }//GEN-LAST:event_UbahNoTelponActionPerformed

    private void LogoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBTNActionPerformed
        SesiLogin.clearSesiLogin();

        Login LoginScreen = new Login();
        LoginScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutBTNActionPerformed

    private void cariBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBTNActionPerformed
        String namaresto = cariRestoInput.getText();
        
        if (namaresto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap masukan nama restoran yang ingin dicari");
        } else {
            namaRestoDisplay.setText(namaresto);
            Restoran newResto = restoCNTRL.getRestoByNama(namaresto);
            if (newResto == null) {
               JOptionPane.showMessageDialog(this, "restoran tidak ada"); 
            } else {
                loadDaftarMejaByNamaResto(namaresto, newResto.getIdRestoran());
            }
        }

    }//GEN-LAST:event_cariBTNActionPerformed

    private void daftarMejaRestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarMejaRestoMouseClicked
        int selectedRow = daftarMejaResto.getSelectedRow();
        
        if (selectedRow != -1) {
            int idMeja = (int) modelDaftarMeja.getValueAt(selectedRow, 0);
            int idResto = (int) modelDaftarMeja.getValueAt(selectedRow, 1);
            int jumlahKursi = (int) modelDaftarMeja.getValueAt(selectedRow, 2);
            String status = modelDaftarMeja.getValueAt(selectedRow, 3).toString();
            String namaResto = cariRestoInput.getText();
            
            BookingMeja bookMeja = new BookingMeja();
            bookMeja.BookingMeja(namaResto, status, jumlahKursi, idMeja, idResto);
            bookMeja.setVisible(true);
        }
    }//GEN-LAST:event_daftarMejaRestoMouseClicked

    private void RefreshBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshBTNActionPerformed
        daftarRiwayatBook.removeAll();
        int rows = modelHistoryBook.getRowCount();
        for(int i = rows - 1; i >= 0; i--){
            modelHistoryBook.removeRow(i);
        }
        
        loadRiawayatBooking(SesiLogin.getId());
    }//GEN-LAST:event_RefreshBTNActionPerformed

    private void RefreshBTN02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshBTN02ActionPerformed
        cariRestoInput.setText("");
        
        daftarMejaResto.removeAll();
        int rows = modelDaftarMeja.getRowCount();
        
        for(int i = rows - 1; i >= 0; i--){
            modelDaftarMeja.removeRow(i);
        }
    }//GEN-LAST:event_RefreshBTN02ActionPerformed

    private void daftarRiwayatBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarRiwayatBookMouseClicked
        int selectedRow = daftarRiwayatBook.getSelectedRow();
        
        if(selectedRow != -1){
            int idResto = (int) modelHistoryBook.getValueAt(selectedRow, 0);
            String namaResto = modelHistoryBook.getValueAt(selectedRow, 1).toString();
            int idMeja = (int) modelHistoryBook.getValueAt(selectedRow, 2);
            String waktuDatang = modelHistoryBook.getValueAt(selectedRow, 3).toString();
            String status = modelHistoryBook.getValueAt(selectedRow, 4).toString();
            
            System.out.println(idMeja);
            cancelPemesanan cancelpemesanan = new cancelPemesanan();
            cancelpemesanan.cancelPemesanan(namaResto, status, waktuDatang, idMeja, idResto);
            cancelpemesanan.setVisible(true);
        }
    }//GEN-LAST:event_daftarRiwayatBookMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPemesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPemesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPemesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPemesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPemesan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutBTN;
    private javax.swing.JLabel NamaUserProfile;
    private javax.swing.JLabel NoTelpUserProfile;
    private javax.swing.JButton RefreshBTN;
    private javax.swing.JButton RefreshBTN02;
    private javax.swing.JButton UbahNama;
    private javax.swing.JButton UbahNoTelpon;
    private javax.swing.JButton UbahPassword;
    private javax.swing.JButton UbahUsername;
    private javax.swing.JLabel UsernameUserProfile;
    private javax.swing.JButton cariBTN;
    private javax.swing.JTextField cariRestoInput;
    private javax.swing.JTable daftarMejaResto;
    private javax.swing.JTable daftarRiwayatBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel namaPemesanDisplay;
    private javax.swing.JLabel namaRestoDisplay;
    // End of variables declaration//GEN-END:variables
}
